### PR TITLE
Fix position of value and currency in add_to_cart

### PR DESCRIPTION
**Pull request by anvanza**
Fix the position of value and currency in the add_to_cart.

https://developers.google.com/analytics/devguides/collection/ga4/ecommerce?client_type=gtm#add_or_remove_an_item_from_a_shopping_cart

### CODE REVIEW

**Comment by samicoman** [comment]
@anvanza, I think this link is more up-to-date: https://developers.google.com/analytics/devguides/collection/ga4/reference/events?client_type=gtag#add_to_cart

**Comment by anvanza** [comment]
@samicoman , That's just the gtag implementation instead of the dataLayer but essentially it's the same.

https://developers.google.com/analytics/devguides/collection/ga4/reference/events?client_type=gtm#add_to_cart

The PR is valid according to the docs.

**Comment by samicoman** [comment]
As you said, it's the same thing. Gtag uses the dataLayer. 

I've been following the documentation for more than 1 year now. They had issues keeping everything updated everywhere. The link I posted has the most consistent information and is the most up-to-date in my opinion.

Also, I'm using this module on a bunch of websites and has good results in GA as it is.

**Comment by jissereitsma** [comment]
@anvanza @samicoman Thanks so much for this fix. I'll include it in the next release!

**Comment by samicoman** [comment]
> @anvanza @samicoman Thanks so much for this fix. I'll include it in the next release!

I do not agree with the fix. I think it contradicts the documentation on one hand, and I have good results with the extension as it is. If this change is released, I'll have to apply a patch to revert it on all the projects that are using the extension.

**Comment by anvanza** [comment]
Hi @samicoman , What do you mean? The documentation clearly status that it should be in the ecommerce key?
Screenshot 2023-09-06 at 17 40 56

**Comment by jissereitsma** [comment]
Indeed this is confusing. However, the following link shows an example where the `currency` and the `value` are within the `ecommerce` object: https://developers.google.com/analytics/devguides/collection/ga4/ecommerce?client_type=gtm#add_or_remove_an_item_from_a_shopping_cart

What is the difference in the URL? In your case @samicoman the client type is `gtag`. In my case (and I guess @anvanza was referring to this) the client type is `gtm`. And this extension is really only about GTM. So personally I would say that we should follow the GTM standard. (And my guess is that I implemented earlier wrongly the gtag version because I also didn't catch this difference.)

As I see it, @samicoman , the Yireo extension did apply the `gtag` standard for GTM instead and it worked all along. It's a bit scary, but do you think you could try to keep this fix anyway and see if it makes a difference. (And perhaps Google itself actually does not really care.)

**Comment by samicoman** [comment]
@jissereitsma @anvanza, the link you provided is more like a tutorial, a general "how-to", a "hello-world", however you want to call it. And my belief is it is outdated. The one I provided is the reference and I saw it being updated consistently over time.

The URLs having `gtag` or `gtm` is just a coincidence (how they got indexed by Google). In the end, the goal of the module is to push the data to the DataLayer and get it with GTM. gtag does not have a say on this.

Here's an URL with`gtm` instead of `gtag`: https://developers.google.com/analytics/devguides/collection/ga4/reference/events?client_type=gtm#add_to_cart . You will see it takes you to the exact same place and the examples do not change.

**Comment by jissereitsma** [comment]
I think we are reading things different. If I go to the URL you posted above directly, it gives me an "Service Unavailable" error. If I take the URL instead and remove the `?client_type` and the `#add_to_cart`, I'm able to navigate to the page https://developers.google.com/analytics/devguides/collection/ga4/reference/events. If I then in the top select "Tag Manager" and jump to "add_to_cart" on the right, it brings me to the following JSON snippet (leaving out the items):

```json
dataLayer.push({ ecommerce: null });  // Clear the previous ecommerce object.
dataLayer.push({
  event: "add_to_cart",
  ecommerce: {
    currency: "USD",
    value: 7.77,
    items: []
  }
});
```

To me, this shows the fix of @anvanza is solid.

**Comment by samicoman** [comment]
@jissereitsma, @anvanza, I must have been drunk, or something (even if I don't drink). Now I'm reading the same thing and I agree with the solution. Sorry for the noise. I have checked just now the projects running the extension and they have a patch for this issue. That's why I things were working fine, because they were patched.

**Comment by jissereitsma** [comment]
@samicoman No, I don't think there is anything wrong with you, I think I suffered from the same issue, which is why the structure was first correct and then corrected by @anvanza . It's the Google doc system we should blame, it is just confusing :)

**Pull request merged**
