### PR TITLE
Fix PHP 8.2 deprecation error on dynamic creation

### PR DESCRIPTION
**Pull request by peterjaap**
This is based on 2.1.8, so this change needs to be released in 2.1.9

### CODE REVIEW

**Comment by jissereitsma** [comment]
I'm afraid I'm no longer maintaining version 2. It was lacking GA3 support which will be outdated in a few months anyway. So it is best to upgrade to GA4 anyway, thus version 3 of this Yireo module ...

**Comment by peterjaap** [comment]
@jissereitsma I know, the trouble is that the Hyvä compat module requires ^2.0.5; https://gitlab.hyva.io/hyva-themes/hyva-compat/magento2-yireo-googletagmanager2/-/blob/main/composer.json#L8

**Comment by peterjaap** [comment]
@jissereitsma righto, check! Thanks for the clarification.

**Comment by peterjaap** [comment]
Patch to use with `vaimo/composer-patches`;

```
{
   "yireo/magento2-googletagmanager2": {
      "Fix PHP 8.2 error": {
        "source": "https://patch-diff.githubusercontent.com/raw/yireo/Yireo_GoogleTagManager2/pull/136.diff",
        "link": "https://github.com/yireo/Yireo_GoogleTagManager2/pull/136",
        "level": 1
      }
    }
}
```

**Comment by jissereitsma** [comment]
I'm going to add this patch to the docs also! Thanks!

**Pull request closed without merging**
