### PR TITLE
version string in composer.json is not recommended when using GIT

### PR DESCRIPTION
**Pull request by ThomasNegeli**
As of https://getcomposer.org/doc/02-libraries.md#library-versioning

### CODE REVIEW

**Comment by jissereitsma** [comment]
Thanks. Unfortunately, the Magento coding standard are different than the recommendations of composer itself. Currently, in the Magento ecosystem, it is recommended to rely on versioning via composer instead of `module.xml` (to prevent endless setup upgrades that are not needed). However, because there are more ways to install an extension besides using composer (`app/code` or just using composer to install direct ZIPs) so that the version in `composer.json` needs to remain.

**Comment by ThomasNegeli** [comment]
@jissereitsma I remember the discussion on twitter about this topic.
Now we have a version in the module.xml, in the composer.json and in the GIT Tag.
I love the Magento way of doing things.

**Comment by jissereitsma** [comment]
It is not that bad. The version of `composer.json` is supposed to be equal to the git tag. They are mutual interchangable (I thought that was an English saying). However, the `module.xml` only manages the version of the database setup, not the code setup.

**Comment by ThomasNegeli** [comment]
@jissereitsma thanks for you explanation

**Pull request closed without merging**
